name: Update

on:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Update
        run: node main.js
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push if changed
        run: |-
          git diff
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git pull
          git add -A
          git commit -m "🤖 Auto update README" || exit 0
          git push
      - name: Build
        run: |-
          mkdir public
          cp -r ./data ./public/
          cp ./index.html ./public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
